services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY:-https://verdaccio.moisad.info}

    restart: unless-stopped
    profiles: [app]
    ports:
      - '127.0.0.1:3000:3000'
    expose:
      - 3000

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    expose:
      - 6379
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9001:9001'
    expose:
      - 9000
      - 9001
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
